version: "3.9"

services:
  birdhouse:
    container_name: birdhouse-api
    build: .
    restart: unless-stopped
    env_file:
      ./env.docker.birdhouse-api
    ports:
      - "3000:3000"

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      ./env.docker.mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data: